stages:
  - deploy

master_deployment:
  stage: deploy
  script:
    - sudo mkdir -p /home/amvara/projects/cometa_website || true
    - sudo cp -rp . /home/amvara/projects/cometa_website/.
  only:
    refs:
      - master

stage_deployment:
  stage: deploy
  script:
    - sudo mkdir -p /home/amvara/projects/cometa_website_stage || true
    - sudo cp -rp . /home/amvara/projects/cometa_website_stage/.
  only:
    refs:
      - Stage