version: "3"

services:
    nginx:
      image: richarvey/nginx-php-fpm
      container_name: cometa_website
      restart: always
      volumes:
        - ./:/cometa_website
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - ./code/:/var/www/html/
      working_dir: /cometa_website
      environment:
        - PHP_ERRORS_STDERR=TRUE
      ports:
        - "8010:80"