version: "3"

services:
    nginx:
      image: nginx:latest
      container_name: cometa_website
      restart: always
      volumes:
        - ./:/cometa_website
        - ./default.conf:/etc/nginx/conf.d/default.conf
        - "/home/amvara/projects/cometa/cometa_website/code/.:/usr/share/nginx/html/."
      working_dir: /cometa_website
      ports:
        - "8010:80"
      command: [nginx-debug, '-g', 'daemon off;']