version: "3"

services:
    nginx:
      image: nginx:alpine
      container_name: cometa_website_stage
      restart: always
      volumes:
        - ./:/cometa_website
        - ./code/:/usr/share/nginx/html
        - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
      working_dir: /cometa_website
      ports:
        - "8011:80"
