version: "3"

services:
    nginx:
      image: nginx:alpine
      container_name: cometa_website_stage
      restart: always
      volumes:
        - ./:/cometa_website
        - ./code/:/var/www/html/
      working_dir: /cometa_website
      ports:
        - "8011:80"